packages:
  # - "packages/skeuomusic"
  - "packages/skeuomusic-react"
  - "packages/spotify-web-client"

catalog:
  "@types/node": "24.13.3"
  typescript: "6.0.3"
  vitest: "5.0.1"
  "@vitest/browser": "5.0.1"
  "@vitest/browser-playwright": "5.0.1"

allowBuilds:
  "@nestjs/core": false
  "@openapitools/openapi-generator-cli": true
  "@parcel/watcher": true
  esbuild: true
