packages:
  - "packages/skeuomusic-react"
  - "packages/spotify-web-client"

catalog:
  "@types/node": "24.12.4"
  typescript: "6.0.2"
  vitest: "4.1.8"
  "@vitest/browser": "4.1.8"
  "@vitest/browser-playwright": "4.1.8"

allowBuilds:
  "@nestjs/core": false
  "@openapitools/openapi-generator-cli": true
  "@parcel/watcher": true
  esbuild: true
