/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * Spotify Web API with fixes and improvements from sonallux & finn-wa
 *
 * The version of the OpenAPI document: 9979e00
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  ChapterObject,
  GetAnAlbum401Response,
  PagingSimplifiedChapterObject,
} from "../models/index";

export interface ChaptersApiGetAChapterRequest {
  id: string;
  market?: string;
}

export interface ChaptersApiGetAudiobookChaptersRequest {
  id: string;
  market?: string;
  limit?: number;
  offset?: number;
}

/**
 *
 */
export class ChaptersApi extends runtime.BaseAPI {
  /**
   * Get Spotify catalog information for a single audiobook chapter. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Get a Chapter
   */
  async getAChapterRaw(
    requestParameters: ChaptersApiGetAChapterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ChapterObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAChapter().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", []);
    }

    let urlPath = `/chapters/{id}`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for a single audiobook chapter. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Get a Chapter
   */
  async getAChapter(
    requestParameters: ChaptersApiGetAChapterRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ChapterObject> {
    const response = await this.getAChapterRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an audiobook\'s chapters. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Get Audiobook Chapters
   */
  async getAudiobookChaptersRaw(
    requestParameters: ChaptersApiGetAudiobookChaptersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSimplifiedChapterObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAudiobookChapters().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", []);
    }

    let urlPath = `/audiobooks/{id}/chapters`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an audiobook\'s chapters. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.
   * Get Audiobook Chapters
   */
  async getAudiobookChapters(
    requestParameters: ChaptersApiGetAudiobookChaptersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSimplifiedChapterObject> {
    const response = await this.getAudiobookChaptersRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
