/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * Spotify Web API with fixes and improvements from sonallux & finn-wa
 *
 * The version of the OpenAPI document: 9979e00
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  EpisodeObject,
  GetAnAlbum401Response,
  PagingSavedEpisodeObject,
  PagingSimplifiedEpisodeObject,
} from "../models/index";

export interface EpisodesApiGetAShowsEpisodesRequest {
  id: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface EpisodesApiGetAnEpisodeRequest {
  id: string;
  market?: string;
}

export interface EpisodesApiGetUsersSavedEpisodesRequest {
  market?: string;
  limit?: number;
  offset?: number;
}

/**
 *
 */
export class EpisodesApi extends runtime.BaseAPI {
  /**
   * Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
   * Get Show Episodes
   */
  async getAShowsEpisodesRaw(
    requestParameters: EpisodesApiGetAShowsEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSimplifiedEpisodeObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAShowsEpisodes().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "user-read-playback-position",
      ]);
    }

    let urlPath = `/shows/{id}/episodes`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
   * Get Show Episodes
   */
  async getAShowsEpisodes(
    requestParameters: EpisodesApiGetAShowsEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSimplifiedEpisodeObject> {
    const response = await this.getAShowsEpisodesRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get Spotify catalog information for a single episode identified by its unique Spotify ID.
   * Get Episode
   */
  async getAnEpisodeRaw(
    requestParameters: EpisodesApiGetAnEpisodeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<EpisodeObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnEpisode().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "user-read-playback-position",
      ]);
    }

    let urlPath = `/episodes/{id}`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for a single episode identified by its unique Spotify ID.
   * Get Episode
   */
  async getAnEpisode(
    requestParameters: EpisodesApiGetAnEpisodeRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<EpisodeObject> {
    const response = await this.getAnEpisodeRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a list of the episodes saved in the current Spotify user\'s library.
   * Get User\'s Saved Episodes
   */
  async getUsersSavedEpisodesRaw(
    requestParameters: EpisodesApiGetUsersSavedEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedEpisodeObject>> {
    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "user-library-read",
        "user-read-playback-position",
      ]);
    }

    let urlPath = `/me/episodes`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the episodes saved in the current Spotify user\'s library.
   * Get User\'s Saved Episodes
   */
  async getUsersSavedEpisodes(
    requestParameters: EpisodesApiGetUsersSavedEpisodesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedEpisodeObject> {
    const response = await this.getUsersSavedEpisodesRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
