/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * Spotify Web API with fixes and improvements from sonallux & finn-wa
 *
 * The version of the OpenAPI document: 39207c4
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class
 * manually.
 */

import * as runtime from "../runtime";
import type {
  ChangePlaylistDetailsRequest,
  CreatePlaylistRequest,
  ErrorObject,
  GetAnAlbum401Response,
  GetFollowed200Response,
  PagingArtistObject,
  PagingPlaylistObject,
  PagingSavedAlbumObject,
  PagingSavedAudiobookObject,
  PagingSavedEpisodeObject,
  PagingSavedShowObject,
  PagingSavedTrackObject,
  PagingTrackObject,
  PlaylistObject,
} from "../models/index";

export interface LibraryApiChangePlaylistDetailsOperationRequest {
  playlistId: string;
  changePlaylistDetailsRequest?: ChangePlaylistDetailsRequest;
}

export interface LibraryApiCheckLibraryContainsRequest {
  uris: string;
}

export interface LibraryApiCreatePlaylistOperationRequest {
  createPlaylistRequest?: CreatePlaylistRequest;
}

export interface LibraryApiGetAListOfCurrentUsersPlaylistsRequest {
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetFollowedRequest {
  type: GetFollowedTypeEnum;
  after?: string;
  limit?: number;
}

export interface LibraryApiGetUsersSavedAlbumsRequest {
  limit?: number;
  offset?: number;
  market?: string;
}

export interface LibraryApiGetUsersSavedAudiobooksRequest {
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetUsersSavedEpisodesRequest {
  market?: string;
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetUsersSavedShowsRequest {
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetUsersSavedTracksRequest {
  market?: string;
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetUsersTopArtistsRequest {
  timeRange?: string;
  limit?: number;
  offset?: number;
}

export interface LibraryApiGetUsersTopTracksRequest {
  timeRange?: string;
  limit?: number;
  offset?: number;
}

export interface LibraryApiRemoveLibraryItemsRequest {
  uris: string;
}

export interface LibraryApiSaveLibraryItemsRequest {
  uris: string;
}

export class LibraryApi extends runtime.BaseAPI {
  /**
   * Change a playlist's name and public/private state. (The user must, of course, own
   * the playlist.) Change Playlist Details
   */
  async changePlaylistDetailsRaw(
    requestParameters: LibraryApiChangePlaylistDetailsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling changePlaylistDetails().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["changePlaylistDetailsRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Change a playlist's name and public/private state. (The user must, of course, own
   * the playlist.) Change Playlist Details
   */
  async changePlaylistDetails(
    requestParameters: LibraryApiChangePlaylistDetailsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.changePlaylistDetailsRaw(requestParameters, initOverrides);
  }

  /**
   * Check if one or more items are already saved in the current user's library. Accepts
   * Spotify URIs for tracks, albums, episodes, shows, audiobooks, artists, users, and
   * playlists. Check User's Saved Items
   */
  async checkLibraryContainsRaw(
    requestParameters: LibraryApiCheckLibraryContainsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<boolean>>> {
    if (requestParameters["uris"] == null) {
      throw new runtime.RequiredError(
        "uris",
        'Required parameter "uris" was null or undefined when calling checkLibraryContains().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["uris"] != null) {
      queryParameters["uris"] = requestParameters["uris"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read", "user-follow-read", "playlist-read-private"],
      );
    }

    let urlPath = `/me/library/contains`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   * Check if one or more items are already saved in the current user's library. Accepts
   * Spotify URIs for tracks, albums, episodes, shows, audiobooks, artists, users, and
   * playlists. Check User's Saved Items
   */
  async checkLibraryContains(
    requestParameters: LibraryApiCheckLibraryContainsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<boolean>> {
    const response = await this.checkLibraryContainsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Create a playlist for the current Spotify user. (The playlist will be empty until
   * you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).) Each
   * user is generally limited to a maximum of 11000 playlists. Create Playlist
   */
  async createPlaylistRaw(
    requestParameters: LibraryApiCreatePlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PlaylistObject>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/me/playlists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["createPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Create a playlist for the current Spotify user. (The playlist will be empty until
   * you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).) Each
   * user is generally limited to a maximum of 11000 playlists. Create Playlist
   */
  async createPlaylist(
    requestParameters: LibraryApiCreatePlaylistOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PlaylistObject> {
    const response = await this.createPlaylistRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a list of the playlists owned or followed by the current Spotify user.
   * Get Current User\'s Playlists
   */
  async getAListOfCurrentUsersPlaylistsRaw(
    requestParameters: LibraryApiGetAListOfCurrentUsersPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingPlaylistObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-read-private"],
      );
    }

    let urlPath = `/me/playlists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the playlists owned or followed by the current Spotify user.
   * Get Current User\'s Playlists
   */
  async getAListOfCurrentUsersPlaylists(
    requestParameters: LibraryApiGetAListOfCurrentUsersPlaylistsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingPlaylistObject> {
    const response = await this.getAListOfCurrentUsersPlaylistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get the current user\'s followed artists.
   * Get Followed Artists
   */
  async getFollowedRaw(
    requestParameters: LibraryApiGetFollowedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetFollowed200Response>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling getFollowed().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["after"] != null) {
      queryParameters["after"] = requestParameters["after"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-read"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s followed artists.
   * Get Followed Artists
   */
  async getFollowed(
    requestParameters: LibraryApiGetFollowedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetFollowed200Response> {
    const response = await this.getFollowedRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a list of the albums saved in the current Spotify user's 'Your Music' library.
   * Get User's Saved Albums
   */
  async getUsersSavedAlbumsRaw(
    requestParameters: LibraryApiGetUsersSavedAlbumsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedAlbumObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/albums`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the albums saved in the current Spotify user's 'Your Music' library.
   * Get User's Saved Albums
   */
  async getUsersSavedAlbums(
    requestParameters: LibraryApiGetUsersSavedAlbumsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedAlbumObject> {
    const response = await this.getUsersSavedAlbumsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a list of the audiobooks saved in the current Spotify user's 'Your Music'
   * library. Get User's Saved Audiobooks
   */
  async getUsersSavedAudiobooksRaw(
    requestParameters: LibraryApiGetUsersSavedAudiobooksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedAudiobookObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/audiobooks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the audiobooks saved in the current Spotify user's 'Your Music'
   * library. Get User's Saved Audiobooks
   */
  async getUsersSavedAudiobooks(
    requestParameters: LibraryApiGetUsersSavedAudiobooksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedAudiobookObject> {
    const response = await this.getUsersSavedAudiobooksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the episodes saved in the current Spotify user\'s library.
   * Get User\'s Saved Episodes
   */
  async getUsersSavedEpisodesRaw(
    requestParameters: LibraryApiGetUsersSavedEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedEpisodeObject>> {
    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read", "user-read-playback-position"],
      );
    }

    let urlPath = `/me/episodes`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the episodes saved in the current Spotify user\'s library.
   * Get User\'s Saved Episodes
   */
  async getUsersSavedEpisodes(
    requestParameters: LibraryApiGetUsersSavedEpisodesRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedEpisodeObject> {
    const response = await this.getUsersSavedEpisodesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of shows saved in the current Spotify user's library. Optional
   * parameters can be used to limit the number of shows returned. Get User's Saved
   * Shows
   */
  async getUsersSavedShowsRaw(
    requestParameters: LibraryApiGetUsersSavedShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedShowObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/shows`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of shows saved in the current Spotify user's library. Optional
   * parameters can be used to limit the number of shows returned. Get User's Saved
   * Shows
   */
  async getUsersSavedShows(
    requestParameters: LibraryApiGetUsersSavedShowsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedShowObject> {
    const response = await this.getUsersSavedShowsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a list of the songs saved in the current Spotify user's 'Your Music' library.
   * Get User's Saved Tracks
   */
  async getUsersSavedTracksRaw(
    requestParameters: LibraryApiGetUsersSavedTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedTrackObject>> {
    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/tracks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the songs saved in the current Spotify user's 'Your Music' library.
   * Get User's Saved Tracks
   */
  async getUsersSavedTracks(
    requestParameters: LibraryApiGetUsersSavedTracksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedTrackObject> {
    const response = await this.getUsersSavedTracksRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get the current user\'s top artists based on calculated affinity.
   * Get User\'s Top Artists
   */
  async getUsersTopArtistsRaw(
    requestParameters: LibraryApiGetUsersTopArtistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingArtistObject>> {
    const queryParameters: any = {};

    if (requestParameters["timeRange"] != null) {
      queryParameters["time_range"] = requestParameters["timeRange"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-top-read"],
      );
    }

    let urlPath = `/me/top/artists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s top artists based on calculated affinity.
   * Get User\'s Top Artists
   */
  async getUsersTopArtists(
    requestParameters: LibraryApiGetUsersTopArtistsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingArtistObject> {
    const response = await this.getUsersTopArtistsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get the current user\'s top tracks based on calculated affinity.
   * Get User\'s Top Tracks
   */
  async getUsersTopTracksRaw(
    requestParameters: LibraryApiGetUsersTopTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingTrackObject>> {
    const queryParameters: any = {};

    if (requestParameters["timeRange"] != null) {
      queryParameters["time_range"] = requestParameters["timeRange"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-top-read"],
      );
    }

    let urlPath = `/me/top/tracks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s top tracks based on calculated affinity.
   * Get User\'s Top Tracks
   */
  async getUsersTopTracks(
    requestParameters: LibraryApiGetUsersTopTracksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingTrackObject> {
    const response = await this.getUsersTopTracksRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Remove one or more items from the current user's library. Accepts Spotify URIs for
   * tracks, albums, episodes, shows, audiobooks, users, and playlists. Remove Items
   * from Library
   */
  async removeLibraryItemsRaw(
    requestParameters: LibraryApiRemoveLibraryItemsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["uris"] == null) {
      throw new runtime.RequiredError(
        "uris",
        'Required parameter "uris" was null or undefined when calling removeLibraryItems().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["uris"] != null) {
      queryParameters["uris"] = requestParameters["uris"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify", "user-follow-modify", "playlist-modify-public"],
      );
    }

    let urlPath = `/me/library`;

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Remove one or more items from the current user's library. Accepts Spotify URIs for
   * tracks, albums, episodes, shows, audiobooks, users, and playlists. Remove Items
   * from Library
   */
  async removeLibraryItems(
    requestParameters: LibraryApiRemoveLibraryItemsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removeLibraryItemsRaw(requestParameters, initOverrides);
  }

  /**
   * Add one or more items to the current user's library. Accepts Spotify URIs for
   * tracks, albums, episodes, shows, audiobooks, users, and playlists. Save Items to
   * Library
   */
  async saveLibraryItemsRaw(
    requestParameters: LibraryApiSaveLibraryItemsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["uris"] == null) {
      throw new runtime.RequiredError(
        "uris",
        'Required parameter "uris" was null or undefined when calling saveLibraryItems().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["uris"] != null) {
      queryParameters["uris"] = requestParameters["uris"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-modify", "user-follow-modify", "playlist-modify-public"],
      );
    }

    let urlPath = `/me/library`;

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Add one or more items to the current user's library. Accepts Spotify URIs for
   * tracks, albums, episodes, shows, audiobooks, users, and playlists. Save Items to
   * Library
   */
  async saveLibraryItems(
    requestParameters: LibraryApiSaveLibraryItemsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.saveLibraryItemsRaw(requestParameters, initOverrides);
  }
}

/** @export */
export const GetFollowedTypeEnum = {
  Artist: "artist",
} as const;
export type GetFollowedTypeEnum =
  (typeof GetFollowedTypeEnum)[keyof typeof GetFollowedTypeEnum];
