/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * Spotify Web API with fixes and improvements from sonallux & finn-wa
 *
 * The version of the OpenAPI document: 9979e00
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class
 * manually.
 */

import * as runtime from "../runtime";
import type { GetAnAlbum401Response, Search200Response } from "../models/index";

export interface SearchApiSearchRequest {
  q: string;
  type: Array<SearchTypeEnum>;
  market?: string;
  limit?: number;
  offset?: number;
  includeExternal?: SearchIncludeExternalEnum;
}

export class SearchApi extends runtime.BaseAPI {
  /**
   * Get Spotify catalog information about albums, artists, playlists, tracks, shows,
   * episodes or audiobooks that match a keyword string. Audiobooks are only available
   * within the US, UK, Canada, Ireland, New Zealand and Australia markets. Search for
   * Item
   */
  async searchRaw(
    requestParameters: SearchApiSearchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Search200Response>> {
    if (requestParameters["q"] == null) {
      throw new runtime.RequiredError(
        "q",
        'Required parameter "q" was null or undefined when calling search().',
      );
    }

    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling search().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["q"] != null) {
      queryParameters["q"] = requestParameters["q"];
    }

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"]!.join(
        runtime.COLLECTION_FORMATS["csv"],
      );
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    if (requestParameters["includeExternal"] != null) {
      queryParameters["include_external"] = requestParameters["includeExternal"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/search`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about albums, artists, playlists, tracks, shows,
   * episodes or audiobooks that match a keyword string. Audiobooks are only available
   * within the US, UK, Canada, Ireland, New Zealand and Australia markets. Search for
   * Item
   */
  async search(
    requestParameters: SearchApiSearchRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Search200Response> {
    const response = await this.searchRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/** @export */
export const SearchTypeEnum = {
  Album: "album",
  Artist: "artist",
  Playlist: "playlist",
  Track: "track",
  Show: "show",
  Episode: "episode",
  Audiobook: "audiobook",
} as const;
export type SearchTypeEnum = (typeof SearchTypeEnum)[keyof typeof SearchTypeEnum];
/** @export */
export const SearchIncludeExternalEnum = {
  Audio: "audio",
} as const;
export type SearchIncludeExternalEnum =
  (typeof SearchIncludeExternalEnum)[keyof typeof SearchIncludeExternalEnum];
