/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * Spotify Web API with fixes and improvements from sonallux & finn-wa
 *
 * The version of the OpenAPI document: 9979e00
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class
 * manually.
 */

import * as runtime from "../runtime";
import type {
  AddItemsToPlaylistRequest,
  GetAnAlbum401Response,
  PagingPlaylistTrackObject,
  PagingSavedTrackObject,
  PagingSimplifiedTrackObject,
  PagingTrackObject,
  RemoveItemsPlaylistRequest,
  ReorderOrReplacePlaylistsItems200Response,
  ReorderOrReplacePlaylistsItemsRequest,
  TrackObject,
} from "../models/index";

export interface TracksApiAddItemsToPlaylistOperationRequest {
  playlistId: string;
  position?: number;
  uris?: string;
  addItemsToPlaylistRequest?: AddItemsToPlaylistRequest;
}

export interface TracksApiGetAnAlbumsTracksRequest {
  id: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface TracksApiGetPlaylistsItemsRequest {
  playlistId: string;
  market?: string;
  fields?: string;
  limit?: number;
  offset?: number;
  additionalTypes?: string;
}

export interface TracksApiGetTrackRequest {
  id: string;
  market?: string;
}

export interface TracksApiGetUsersSavedTracksRequest {
  market?: string;
  limit?: number;
  offset?: number;
}

export interface TracksApiGetUsersTopTracksRequest {
  timeRange?: string;
  limit?: number;
  offset?: number;
}

export interface TracksApiRemoveItemsPlaylistOperationRequest {
  playlistId: string;
  removeItemsPlaylistRequest?: RemoveItemsPlaylistRequest;
}

export interface TracksApiReorderOrReplacePlaylistsItemsOperationRequest {
  playlistId: string;
  uris?: string;
  reorderOrReplacePlaylistsItemsRequest?: ReorderOrReplacePlaylistsItemsRequest;
}

export class TracksApi extends runtime.BaseAPI {
  /**
   * Add one or more items to a user\'s playlist.
   * Add Items to Playlist
   */
  async addItemsToPlaylistRaw(
    requestParameters: TracksApiAddItemsToPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ReorderOrReplacePlaylistsItems200Response>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling addItemsToPlaylist().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["position"] != null) {
      queryParameters["position"] = requestParameters["position"];
    }

    if (requestParameters["uris"] != null) {
      queryParameters["uris"] = requestParameters["uris"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/items`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["addItemsToPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Add one or more items to a user\'s playlist.
   * Add Items to Playlist
   */
  async addItemsToPlaylist(
    requestParameters: TracksApiAddItemsToPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ReorderOrReplacePlaylistsItems200Response> {
    const response = await this.addItemsToPlaylistRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an album’s tracks. Optional parameters can be
   * used to limit the number of tracks returned. Get Album Tracks
   */
  async getAnAlbumsTracksRaw(
    requestParameters: TracksApiGetAnAlbumsTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSimplifiedTrackObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnAlbumsTracks().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/albums/{id}/tracks`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an album’s tracks. Optional parameters can be
   * used to limit the number of tracks returned. Get Album Tracks
   */
  async getAnAlbumsTracks(
    requestParameters: TracksApiGetAnAlbumsTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSimplifiedTrackObject> {
    const response = await this.getAnAlbumsTracksRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get full details of the items of a playlist owned by a Spotify user. **Note**: This
   * endpoint is only accessible for playlists owned by the current user or playlists the
   * user is a collaborator of. A `403 Forbidden` status code will be returned if the user
   * is neither the owner nor a collaborator of the playlist. Get Playlist Items
   */
  async getPlaylistsItemsRaw(
    requestParameters: TracksApiGetPlaylistsItemsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingPlaylistTrackObject>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling getPlaylistsItems().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["fields"] != null) {
      queryParameters["fields"] = requestParameters["fields"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    if (requestParameters["additionalTypes"] != null) {
      queryParameters["additional_types"] = requestParameters["additionalTypes"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-read-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/items`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get full details of the items of a playlist owned by a Spotify user. **Note**: This
   * endpoint is only accessible for playlists owned by the current user or playlists the
   * user is a collaborator of. A `403 Forbidden` status code will be returned if the user
   * is neither the owner nor a collaborator of the playlist. Get Playlist Items
   */
  async getPlaylistsItems(
    requestParameters: TracksApiGetPlaylistsItemsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingPlaylistTrackObject> {
    const response = await this.getPlaylistsItemsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get Spotify catalog information for a single track identified by its unique Spotify
   * ID. Get Track
   */
  async getTrackRaw(
    requestParameters: TracksApiGetTrackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TrackObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getTrack().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/tracks/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for a single track identified by its unique Spotify
   * ID. Get Track
   */
  async getTrack(
    requestParameters: TracksApiGetTrackRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<TrackObject> {
    const response = await this.getTrackRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a list of the songs saved in the current Spotify user\'s \'Your Music\' library.
   * Get User\'s Saved Tracks
   */
  async getUsersSavedTracksRaw(
    requestParameters: TracksApiGetUsersSavedTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedTrackObject>> {
    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/tracks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the songs saved in the current Spotify user\'s \'Your Music\' library.
   * Get User\'s Saved Tracks
   */
  async getUsersSavedTracks(
    requestParameters: TracksApiGetUsersSavedTracksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedTrackObject> {
    const response = await this.getUsersSavedTracksRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get the current user\'s top tracks based on calculated affinity.
   * Get User\'s Top Tracks
   */
  async getUsersTopTracksRaw(
    requestParameters: TracksApiGetUsersTopTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingTrackObject>> {
    const queryParameters: any = {};

    if (requestParameters["timeRange"] != null) {
      queryParameters["time_range"] = requestParameters["timeRange"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-top-read"],
      );
    }

    let urlPath = `/me/top/tracks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s top tracks based on calculated affinity.
   * Get User\'s Top Tracks
   */
  async getUsersTopTracks(
    requestParameters: TracksApiGetUsersTopTracksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingTrackObject> {
    const response = await this.getUsersTopTracksRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Remove one or more items from a user\'s playlist.
   * Remove Playlist Items
   */
  async removeItemsPlaylistRaw(
    requestParameters: TracksApiRemoveItemsPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ReorderOrReplacePlaylistsItems200Response>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling removeItemsPlaylist().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/items`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["removeItemsPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Remove one or more items from a user\'s playlist.
   * Remove Playlist Items
   */
  async removeItemsPlaylist(
    requestParameters: TracksApiRemoveItemsPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ReorderOrReplacePlaylistsItems200Response> {
    const response = await this.removeItemsPlaylistRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Either reorder or replace items in a playlist depending on the request's parameters.
   * To reorder items, include `range_start`, `insert_before`, `range_length` and
   * `snapshot_id` in the request's body. To replace items, include `uris` as either a
   * query parameter or in the request's body. Replacing items in a playlist will
   * overwrite its existing items. This operation can be used for replacing or clearing
   * items in a playlist. <br/> **Note**: Replace and reorder are mutually exclusive
   * operations which share the same endpoint, but have different parameters. These
   * operations can't be applied together in a single request. Update Playlist Items
   */
  async reorderOrReplacePlaylistsItemsRaw(
    requestParameters: TracksApiReorderOrReplacePlaylistsItemsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ReorderOrReplacePlaylistsItems200Response>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling reorderOrReplacePlaylistsItems().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["uris"] != null) {
      queryParameters["uris"] = requestParameters["uris"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["playlist-modify-public", "playlist-modify-private"],
      );
    }

    let urlPath = `/playlists/{playlist_id}/items`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["reorderOrReplacePlaylistsItemsRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Either reorder or replace items in a playlist depending on the request's parameters.
   * To reorder items, include `range_start`, `insert_before`, `range_length` and
   * `snapshot_id` in the request's body. To replace items, include `uris` as either a
   * query parameter or in the request's body. Replacing items in a playlist will
   * overwrite its existing items. This operation can be used for replacing or clearing
   * items in a playlist. <br/> **Note**: Replace and reorder are mutually exclusive
   * operations which share the same endpoint, but have different parameters. These
   * operations can't be applied together in a single request. Update Playlist Items
   */
  async reorderOrReplacePlaylistsItems(
    requestParameters: TracksApiReorderOrReplacePlaylistsItemsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ReorderOrReplacePlaylistsItems200Response> {
    const response = await this.reorderOrReplacePlaylistsItemsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
