/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * Spotify Web API with fixes and improvements from sonallux & finn-wa
 *
 * The version of the OpenAPI document: 9979e00
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class
 * manually.
 */

import * as runtime from "../runtime";
import type {
  GetAnAlbum401Response,
  GetFollowed200Response,
  PagingArtistObject,
  PagingTrackObject,
  PrivateUserObject,
} from "../models/index";

export interface UsersApiGetFollowedRequest {
  type: GetFollowedTypeEnum;
  after?: string;
  limit?: number;
}

export interface UsersApiGetUsersTopArtistsRequest {
  timeRange?: string;
  limit?: number;
  offset?: number;
}

export interface UsersApiGetUsersTopTracksRequest {
  timeRange?: string;
  limit?: number;
  offset?: number;
}

export class UsersApi extends runtime.BaseAPI {
  /**
   * Get detailed profile information about the current user (including the current user's
   * username). Get Current User's Profile
   */
  async getCurrentUsersProfileRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrivateUserObject>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-private", "user-read-email"],
      );
    }

    let urlPath = `/me`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get detailed profile information about the current user (including the current user's
   * username). Get Current User's Profile
   */
  async getCurrentUsersProfile(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrivateUserObject> {
    const response = await this.getCurrentUsersProfileRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get the current user\'s followed artists.
   * Get Followed Artists
   */
  async getFollowedRaw(
    requestParameters: UsersApiGetFollowedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetFollowed200Response>> {
    if (requestParameters["type"] == null) {
      throw new runtime.RequiredError(
        "type",
        'Required parameter "type" was null or undefined when calling getFollowed().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["type"] != null) {
      queryParameters["type"] = requestParameters["type"];
    }

    if (requestParameters["after"] != null) {
      queryParameters["after"] = requestParameters["after"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-follow-read"],
      );
    }

    let urlPath = `/me/following`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s followed artists.
   * Get Followed Artists
   */
  async getFollowed(
    requestParameters: UsersApiGetFollowedRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetFollowed200Response> {
    const response = await this.getFollowedRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get the current user\'s top artists based on calculated affinity.
   * Get User\'s Top Artists
   */
  async getUsersTopArtistsRaw(
    requestParameters: UsersApiGetUsersTopArtistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingArtistObject>> {
    const queryParameters: any = {};

    if (requestParameters["timeRange"] != null) {
      queryParameters["time_range"] = requestParameters["timeRange"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-top-read"],
      );
    }

    let urlPath = `/me/top/artists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s top artists based on calculated affinity.
   * Get User\'s Top Artists
   */
  async getUsersTopArtists(
    requestParameters: UsersApiGetUsersTopArtistsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingArtistObject> {
    const response = await this.getUsersTopArtistsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get the current user\'s top tracks based on calculated affinity.
   * Get User\'s Top Tracks
   */
  async getUsersTopTracksRaw(
    requestParameters: UsersApiGetUsersTopTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingTrackObject>> {
    const queryParameters: any = {};

    if (requestParameters["timeRange"] != null) {
      queryParameters["time_range"] = requestParameters["timeRange"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-top-read"],
      );
    }

    let urlPath = `/me/top/tracks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current user\'s top tracks based on calculated affinity.
   * Get User\'s Top Tracks
   */
  async getUsersTopTracks(
    requestParameters: UsersApiGetUsersTopTracksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingTrackObject> {
    const response = await this.getUsersTopTracksRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/** @export */
export const GetFollowedTypeEnum = {
  Artist: "artist",
} as const;
export type GetFollowedTypeEnum =
  (typeof GetFollowedTypeEnum)[keyof typeof GetFollowedTypeEnum];
