/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux You can use
 * Spotify's Web API to discover music and podcasts, manage your Spotify
 * library, control audio playback, and much more. Browse our available Web API
 * endpoints using the sidebar at left, or via the navigation bar on top of this
 * page on smaller screens. In order to make successful Web API requests your
 * app will need a valid access token. One can be obtained through <a
 * href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth
 * 2.0</a>. The base URI for all Web API requests is
 * `https://api.spotify.com/v1`. Need help? See our <a
 * href="https://developer.spotify.com/documentation/web-api/guides/">Web API
 * guides</a> for more information, or visit the <a
 * href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify
 * for Developers community forum</a> to ask questions and connect with other
 * developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import * as runtime from "../runtime";
import type {
  AlbumObject,
  GetAnAlbum401Response,
  PagingArtistDiscographyAlbumObject,
  PagingSavedAlbumObject,
  PagingSimplifiedTrackObject,
} from "../models/index";

export interface AlbumsApiGetAnAlbumRequest {
  id: string;
  market?: string;
}

export interface AlbumsApiGetAnAlbumsTracksRequest {
  id: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface AlbumsApiGetAnArtistsAlbumsRequest {
  id: string;
  includeGroups?: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface AlbumsApiGetUsersSavedAlbumsRequest {
  limit?: number;
  offset?: number;
  market?: string;
}

export class AlbumsApi extends runtime.BaseAPI {
  /** Get Spotify catalog information for a single album. Get Album */
  async getAnAlbumRaw(
    requestParameters: AlbumsApiGetAnAlbumRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AlbumObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnAlbum().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/albums/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /** Get Spotify catalog information for a single album. Get Album */
  async getAnAlbum(
    requestParameters: AlbumsApiGetAnAlbumRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AlbumObject> {
    const response = await this.getAnAlbumRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an album’s tracks. Optional
   * parameters can be used to limit the number of tracks returned. Get Album
   * Tracks
   */
  async getAnAlbumsTracksRaw(
    requestParameters: AlbumsApiGetAnAlbumsTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSimplifiedTrackObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnAlbumsTracks().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/albums/{id}/tracks`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an album’s tracks. Optional
   * parameters can be used to limit the number of tracks returned. Get Album
   * Tracks
   */
  async getAnAlbumsTracks(
    requestParameters: AlbumsApiGetAnAlbumsTracksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSimplifiedTrackObject> {
    const response = await this.getAnAlbumsTracksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an artist's albums. Get Artist's
   * Albums
   */
  async getAnArtistsAlbumsRaw(
    requestParameters: AlbumsApiGetAnArtistsAlbumsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingArtistDiscographyAlbumObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnArtistsAlbums().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["includeGroups"] != null) {
      queryParameters["include_groups"] = requestParameters["includeGroups"];
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/artists/{id}/albums`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an artist's albums. Get Artist's
   * Albums
   */
  async getAnArtistsAlbums(
    requestParameters: AlbumsApiGetAnArtistsAlbumsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingArtistDiscographyAlbumObject> {
    const response = await this.getAnArtistsAlbumsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the albums saved in the current Spotify user's 'Your Music'
   * library. Get User's Saved Albums
   */
  async getUsersSavedAlbumsRaw(
    requestParameters: AlbumsApiGetUsersSavedAlbumsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedAlbumObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/albums`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the albums saved in the current Spotify user's 'Your Music'
   * library. Get User's Saved Albums
   */
  async getUsersSavedAlbums(
    requestParameters: AlbumsApiGetUsersSavedAlbumsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedAlbumObject> {
    const response = await this.getUsersSavedAlbumsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
