/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux You can use
 * Spotify's Web API to discover music and podcasts, manage your Spotify
 * library, control audio playback, and much more. Browse our available Web API
 * endpoints using the sidebar at left, or via the navigation bar on top of this
 * page on smaller screens. In order to make successful Web API requests your
 * app will need a valid access token. One can be obtained through <a
 * href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth
 * 2.0</a>. The base URI for all Web API requests is
 * `https://api.spotify.com/v1`. Need help? See our <a
 * href="https://developer.spotify.com/documentation/web-api/guides/">Web API
 * guides</a> for more information, or visit the <a
 * href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify
 * for Developers community forum</a> to ask questions and connect with other
 * developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import * as runtime from "../runtime";
import type {
  AudiobookObject,
  GetAnAlbum401Response,
  PagingSavedAudiobookObject,
  PagingSimplifiedChapterObject,
} from "../models/index";

export interface AudiobooksApiGetAnAudiobookRequest {
  id: string;
  market?: string;
}

export interface AudiobooksApiGetAudiobookChaptersRequest {
  id: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface AudiobooksApiGetUsersSavedAudiobooksRequest {
  limit?: number;
  offset?: number;
}

export class AudiobooksApi extends runtime.BaseAPI {
  /**
   * Get Spotify catalog information for a single audiobook. Audiobooks are only
   * available within the US, UK, Canada, Ireland, New Zealand and Australia
   * markets. Get an Audiobook
   */
  async getAnAudiobookRaw(
    requestParameters: AudiobooksApiGetAnAudiobookRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AudiobookObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAnAudiobook().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/audiobooks/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for a single audiobook. Audiobooks are only
   * available within the US, UK, Canada, Ireland, New Zealand and Australia
   * markets. Get an Audiobook
   */
  async getAnAudiobook(
    requestParameters: AudiobooksApiGetAnAudiobookRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AudiobookObject> {
    const response = await this.getAnAudiobookRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an audiobook's chapters. Audiobooks
   * are only available within the US, UK, Canada, Ireland, New Zealand and
   * Australia markets. Get Audiobook Chapters
   */
  async getAudiobookChaptersRaw(
    requestParameters: AudiobooksApiGetAudiobookChaptersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSimplifiedChapterObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAudiobookChapters().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        [],
      );
    }

    let urlPath = `/audiobooks/{id}/chapters`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an audiobook's chapters. Audiobooks
   * are only available within the US, UK, Canada, Ireland, New Zealand and
   * Australia markets. Get Audiobook Chapters
   */
  async getAudiobookChapters(
    requestParameters: AudiobooksApiGetAudiobookChaptersRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSimplifiedChapterObject> {
    const response = await this.getAudiobookChaptersRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of the audiobooks saved in the current Spotify user's 'Your
   * Music' library. Get User's Saved Audiobooks
   */
  async getUsersSavedAudiobooksRaw(
    requestParameters: AudiobooksApiGetUsersSavedAudiobooksRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedAudiobookObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/audiobooks`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the audiobooks saved in the current Spotify user's 'Your
   * Music' library. Get User's Saved Audiobooks
   */
  async getUsersSavedAudiobooks(
    requestParameters: AudiobooksApiGetUsersSavedAudiobooksRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedAudiobookObject> {
    const response = await this.getUsersSavedAudiobooksRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
