/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * Spotify Web API with fixes and improvements from sonallux & finn-wa
 *
 * The version of the OpenAPI document: 9979e00
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  AddItemsToPlaylistRequest,
  ChangePlaylistDetailsRequest,
  CreatePlaylistRequest,
  GetAnAlbum401Response,
  ImageObject,
  PagingPlaylistObject,
  PagingPlaylistTrackObject,
  PlaylistObject,
  RemoveItemsPlaylistRequest,
  ReorderOrReplacePlaylistsItems200Response,
  ReorderOrReplacePlaylistsItemsRequest,
} from "../models/index";

export interface PlaylistsApiAddItemsToPlaylistOperationRequest {
  playlistId: string;
  position?: number;
  uris?: string;
  addItemsToPlaylistRequest?: AddItemsToPlaylistRequest;
}

export interface PlaylistsApiChangePlaylistDetailsOperationRequest {
  playlistId: string;
  changePlaylistDetailsRequest?: ChangePlaylistDetailsRequest;
}

export interface PlaylistsApiCreatePlaylistOperationRequest {
  createPlaylistRequest?: CreatePlaylistRequest;
}

export interface PlaylistsApiGetAListOfCurrentUsersPlaylistsRequest {
  limit?: number;
  offset?: number;
}

export interface PlaylistsApiGetPlaylistRequest {
  playlistId: string;
  market?: string;
  fields?: string;
  additionalTypes?: string;
}

export interface PlaylistsApiGetPlaylistCoverRequest {
  playlistId: string;
}

export interface PlaylistsApiGetPlaylistsItemsRequest {
  playlistId: string;
  market?: string;
  fields?: string;
  limit?: number;
  offset?: number;
  additionalTypes?: string;
}

export interface PlaylistsApiRemoveItemsPlaylistOperationRequest {
  playlistId: string;
  removeItemsPlaylistRequest?: RemoveItemsPlaylistRequest;
}

export interface PlaylistsApiReorderOrReplacePlaylistsItemsOperationRequest {
  playlistId: string;
  uris?: string;
  reorderOrReplacePlaylistsItemsRequest?: ReorderOrReplacePlaylistsItemsRequest;
}

export interface PlaylistsApiUploadCustomPlaylistCoverRequest {
  playlistId: string;
  body: string;
}

/**
 *
 */
export class PlaylistsApi extends runtime.BaseAPI {
  /**
   * Add one or more items to a user\'s playlist.
   * Add Items to Playlist
   */
  async addItemsToPlaylistRaw(
    requestParameters: PlaylistsApiAddItemsToPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ReorderOrReplacePlaylistsItems200Response>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling addItemsToPlaylist().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["position"] != null) {
      queryParameters["position"] = requestParameters["position"];
    }

    if (requestParameters["uris"] != null) {
      queryParameters["uris"] = requestParameters["uris"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "playlist-modify-public",
        "playlist-modify-private",
      ]);
    }

    let urlPath = `/playlists/{playlist_id}/items`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["addItemsToPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Add one or more items to a user\'s playlist.
   * Add Items to Playlist
   */
  async addItemsToPlaylist(
    requestParameters: PlaylistsApiAddItemsToPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ReorderOrReplacePlaylistsItems200Response> {
    const response = await this.addItemsToPlaylistRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Change a playlist\'s name and public/private state. (The user must, of course, own the playlist.)
   * Change Playlist Details
   */
  async changePlaylistDetailsRaw(
    requestParameters: PlaylistsApiChangePlaylistDetailsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling changePlaylistDetails().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "playlist-modify-public",
        "playlist-modify-private",
      ]);
    }

    let urlPath = `/playlists/{playlist_id}`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["changePlaylistDetailsRequest"],
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Change a playlist\'s name and public/private state. (The user must, of course, own the playlist.)
   * Change Playlist Details
   */
  async changePlaylistDetails(
    requestParameters: PlaylistsApiChangePlaylistDetailsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.changePlaylistDetailsRaw(requestParameters, initOverrides);
  }

  /**
   * Create a playlist for the current Spotify user. (The playlist will be empty until you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).) Each user is generally limited to a maximum of 11000 playlists.
   * Create Playlist
   */
  async createPlaylistRaw(
    requestParameters: PlaylistsApiCreatePlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PlaylistObject>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "playlist-modify-public",
        "playlist-modify-private",
      ]);
    }

    let urlPath = `/me/playlists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["createPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Create a playlist for the current Spotify user. (The playlist will be empty until you [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).) Each user is generally limited to a maximum of 11000 playlists.
   * Create Playlist
   */
  async createPlaylist(
    requestParameters: PlaylistsApiCreatePlaylistOperationRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PlaylistObject> {
    const response = await this.createPlaylistRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a list of the playlists owned or followed by the current Spotify user.
   * Get Current User\'s Playlists
   */
  async getAListOfCurrentUsersPlaylistsRaw(
    requestParameters: PlaylistsApiGetAListOfCurrentUsersPlaylistsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingPlaylistObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "playlist-read-private",
      ]);
    }

    let urlPath = `/me/playlists`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of the playlists owned or followed by the current Spotify user.
   * Get Current User\'s Playlists
   */
  async getAListOfCurrentUsersPlaylists(
    requestParameters: PlaylistsApiGetAListOfCurrentUsersPlaylistsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingPlaylistObject> {
    const response = await this.getAListOfCurrentUsersPlaylistsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a playlist owned by a Spotify user.
   * Get Playlist
   */
  async getPlaylistRaw(
    requestParameters: PlaylistsApiGetPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PlaylistObject>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling getPlaylist().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["fields"] != null) {
      queryParameters["fields"] = requestParameters["fields"];
    }

    if (requestParameters["additionalTypes"] != null) {
      queryParameters["additional_types"] = requestParameters["additionalTypes"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", []);
    }

    let urlPath = `/playlists/{playlist_id}`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a playlist owned by a Spotify user.
   * Get Playlist
   */
  async getPlaylist(
    requestParameters: PlaylistsApiGetPlaylistRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PlaylistObject> {
    const response = await this.getPlaylistRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get the current image associated with a specific playlist.
   * Get Playlist Cover Image
   */
  async getPlaylistCoverRaw(
    requestParameters: PlaylistsApiGetPlaylistCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ImageObject>>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling getPlaylistCover().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", []);
    }

    let urlPath = `/playlists/{playlist_id}/images`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get the current image associated with a specific playlist.
   * Get Playlist Cover Image
   */
  async getPlaylistCover(
    requestParameters: PlaylistsApiGetPlaylistCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<ImageObject>> {
    const response = await this.getPlaylistCoverRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get full details of the items of a playlist owned by a Spotify user.  **Note**: This endpoint is only accessible for playlists owned by the current user or playlists the user is a collaborator of. A `403 Forbidden` status code will be returned if the user is neither the owner nor a collaborator of the playlist.
   * Get Playlist Items
   */
  async getPlaylistsItemsRaw(
    requestParameters: PlaylistsApiGetPlaylistsItemsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingPlaylistTrackObject>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling getPlaylistsItems().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["fields"] != null) {
      queryParameters["fields"] = requestParameters["fields"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    if (requestParameters["additionalTypes"] != null) {
      queryParameters["additional_types"] = requestParameters["additionalTypes"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "playlist-read-private",
      ]);
    }

    let urlPath = `/playlists/{playlist_id}/items`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get full details of the items of a playlist owned by a Spotify user.  **Note**: This endpoint is only accessible for playlists owned by the current user or playlists the user is a collaborator of. A `403 Forbidden` status code will be returned if the user is neither the owner nor a collaborator of the playlist.
   * Get Playlist Items
   */
  async getPlaylistsItems(
    requestParameters: PlaylistsApiGetPlaylistsItemsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingPlaylistTrackObject> {
    const response = await this.getPlaylistsItemsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Remove one or more items from a user\'s playlist.
   * Remove Playlist Items
   */
  async removeItemsPlaylistRaw(
    requestParameters: PlaylistsApiRemoveItemsPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ReorderOrReplacePlaylistsItems200Response>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling removeItemsPlaylist().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "playlist-modify-public",
        "playlist-modify-private",
      ]);
    }

    let urlPath = `/playlists/{playlist_id}/items`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["removeItemsPlaylistRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Remove one or more items from a user\'s playlist.
   * Remove Playlist Items
   */
  async removeItemsPlaylist(
    requestParameters: PlaylistsApiRemoveItemsPlaylistOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ReorderOrReplacePlaylistsItems200Response> {
    const response = await this.removeItemsPlaylistRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Either reorder or replace items in a playlist depending on the request\'s parameters. To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request\'s body. To replace items, include `uris` as either a query parameter or in the request\'s body. Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist. <br/> **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters. These operations can\'t be applied together in a single request.
   * Update Playlist Items
   */
  async reorderOrReplacePlaylistsItemsRaw(
    requestParameters: PlaylistsApiReorderOrReplacePlaylistsItemsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ReorderOrReplacePlaylistsItems200Response>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling reorderOrReplacePlaylistsItems().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["uris"] != null) {
      queryParameters["uris"] = requestParameters["uris"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "playlist-modify-public",
        "playlist-modify-private",
      ]);
    }

    let urlPath = `/playlists/{playlist_id}/items`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["reorderOrReplacePlaylistsItemsRequest"],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Either reorder or replace items in a playlist depending on the request\'s parameters. To reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request\'s body. To replace items, include `uris` as either a query parameter or in the request\'s body. Replacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist. <br/> **Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters. These operations can\'t be applied together in a single request.
   * Update Playlist Items
   */
  async reorderOrReplacePlaylistsItems(
    requestParameters: PlaylistsApiReorderOrReplacePlaylistsItemsOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ReorderOrReplacePlaylistsItems200Response> {
    const response = await this.reorderOrReplacePlaylistsItemsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Replace the image used to represent a specific playlist.
   * Add Custom Playlist Cover Image
   */
  async uploadCustomPlaylistCoverRaw(
    requestParameters: PlaylistsApiUploadCustomPlaylistCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["playlistId"] == null) {
      throw new runtime.RequiredError(
        "playlistId",
        'Required parameter "playlistId" was null or undefined when calling uploadCustomPlaylistCover().',
      );
    }

    if (requestParameters["body"] == null) {
      throw new runtime.RequiredError(
        "body",
        'Required parameter "body" was null or undefined when calling uploadCustomPlaylistCover().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "image/jpeg";

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "ugc-image-upload",
        "playlist-modify-public",
        "playlist-modify-private",
      ]);
    }

    let urlPath = `/playlists/{playlist_id}/images`;
    urlPath = urlPath.replace(
      `{${"playlist_id"}}`,
      encodeURIComponent(String(requestParameters["playlistId"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["body"] as any,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   * Replace the image used to represent a specific playlist.
   * Add Custom Playlist Cover Image
   */
  async uploadCustomPlaylistCover(
    requestParameters: PlaylistsApiUploadCustomPlaylistCoverRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uploadCustomPlaylistCoverRaw(requestParameters, initOverrides);
  }
}
