/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux You can use
 * Spotify's Web API to discover music and podcasts, manage your Spotify
 * library, control audio playback, and much more. Browse our available Web API
 * endpoints using the sidebar at left, or via the navigation bar on top of this
 * page on smaller screens. In order to make successful Web API requests your
 * app will need a valid access token. One can be obtained through <a
 * href="https://developer.spotify.com/documentation/general/guides/authorization-guide/">OAuth
 * 2.0</a>. The base URI for all Web API requests is
 * `https://api.spotify.com/v1`. Need help? See our <a
 * href="https://developer.spotify.com/documentation/web-api/guides/">Web API
 * guides</a> for more information, or visit the <a
 * href="https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer">Spotify
 * for Developers community forum</a> to ask questions and connect with other
 * developers.
 *
 * The version of the OpenAPI document: 2025.5.18
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * (https://openapi-generator.tech). https://openapi-generator.tech Do not edit
 * the class manually.
 */

import * as runtime from "../runtime";
import type {
  GetAnAlbum401Response,
  PagingSavedShowObject,
  PagingSimplifiedEpisodeObject,
  ShowObject,
} from "../models/index";

export interface ShowsApiGetAShowRequest {
  id: string;
  market?: string;
}

export interface ShowsApiGetAShowsEpisodesRequest {
  id: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface ShowsApiGetUsersSavedShowsRequest {
  limit?: number;
  offset?: number;
}

export class ShowsApi extends runtime.BaseAPI {
  /**
   * Get Spotify catalog information for a single show identified by its unique
   * Spotify ID. Get Show
   */
  async getAShowRaw(
    requestParameters: ShowsApiGetAShowRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ShowObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAShow().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-playback-position"],
      );
    }

    let urlPath = `/shows/{id}`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for a single show identified by its unique
   * Spotify ID. Get Show
   */
  async getAShow(
    requestParameters: ShowsApiGetAShowRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ShowObject> {
    const response = await this.getAShowRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an show’s episodes. Optional
   * parameters can be used to limit the number of episodes returned. Get Show
   * Episodes
   */
  async getAShowsEpisodesRaw(
    requestParameters: ShowsApiGetAShowsEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSimplifiedEpisodeObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAShowsEpisodes().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-read-playback-position"],
      );
    }

    let urlPath = `/shows/{id}/episodes`;
    urlPath = urlPath.replace(
      `{${"id"}}`,
      encodeURIComponent(String(requestParameters["id"])),
    );

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an show’s episodes. Optional
   * parameters can be used to limit the number of episodes returned. Get Show
   * Episodes
   */
  async getAShowsEpisodes(
    requestParameters: ShowsApiGetAShowsEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSimplifiedEpisodeObject> {
    const response = await this.getAShowsEpisodesRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   * Get a list of shows saved in the current Spotify user's library. Optional
   * parameters can be used to limit the number of shows returned. Get User's
   * Saved Shows
   */
  async getUsersSavedShowsRaw(
    requestParameters: ShowsApiGetUsersSavedShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedShowObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken(
        "oauth_2_0",
        ["user-library-read"],
      );
    }

    let urlPath = `/me/shows`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of shows saved in the current Spotify user's library. Optional
   * parameters can be used to limit the number of shows returned. Get User's
   * Saved Shows
   */
  async getUsersSavedShows(
    requestParameters: ShowsApiGetUsersSavedShowsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedShowObject> {
    const response = await this.getUsersSavedShowsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }
}
