/* tslint:disable */
/* eslint-disable */
/**
 * Spotify Web API with fixes and improvements from sonallux
 * Spotify Web API with fixes and improvements from sonallux & finn-wa
 *
 * The version of the OpenAPI document: 9979e00
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  GetAnAlbum401Response,
  PagingSavedShowObject,
  PagingSimplifiedEpisodeObject,
  ShowObject,
} from "../models/index";

export interface ShowsApiGetAShowRequest {
  id: string;
  market?: string;
}

export interface ShowsApiGetAShowsEpisodesRequest {
  id: string;
  market?: string;
  limit?: number;
  offset?: number;
}

export interface ShowsApiGetUsersSavedShowsRequest {
  limit?: number;
  offset?: number;
}

/**
 *
 */
export class ShowsApi extends runtime.BaseAPI {
  /**
   * Get Spotify catalog information for a single show identified by its unique Spotify ID.
   * Get Show
   */
  async getAShowRaw(
    requestParameters: ShowsApiGetAShowRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ShowObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAShow().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "user-read-playback-position",
      ]);
    }

    let urlPath = `/shows/{id}`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information for a single show identified by its unique Spotify ID.
   * Get Show
   */
  async getAShow(
    requestParameters: ShowsApiGetAShowRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ShowObject> {
    const response = await this.getAShowRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
   * Get Show Episodes
   */
  async getAShowsEpisodesRaw(
    requestParameters: ShowsApiGetAShowsEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSimplifiedEpisodeObject>> {
    if (requestParameters["id"] == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling getAShowsEpisodes().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["market"] != null) {
      queryParameters["market"] = requestParameters["market"];
    }

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "user-read-playback-position",
      ]);
    }

    let urlPath = `/shows/{id}/episodes`;
    urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters["id"])));

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.
   * Get Show Episodes
   */
  async getAShowsEpisodes(
    requestParameters: ShowsApiGetAShowsEpisodesRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSimplifiedEpisodeObject> {
    const response = await this.getAShowsEpisodesRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get a list of shows saved in the current Spotify user\'s library. Optional parameters can be used to limit the number of shows returned.
   * Get User\'s Saved Shows
   */
  async getUsersSavedShowsRaw(
    requestParameters: ShowsApiGetUsersSavedShowsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PagingSavedShowObject>> {
    const queryParameters: any = {};

    if (requestParameters["limit"] != null) {
      queryParameters["limit"] = requestParameters["limit"];
    }

    if (requestParameters["offset"] != null) {
      queryParameters["offset"] = requestParameters["offset"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      // oauth required
      headerParameters["Authorization"] = await this.configuration.accessToken("oauth_2_0", [
        "user-library-read",
      ]);
    }

    let urlPath = `/me/shows`;

    const response = await this.request(
      {
        path: urlPath,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response);
  }

  /**
   * Get a list of shows saved in the current Spotify user\'s library. Optional parameters can be used to limit the number of shows returned.
   * Get User\'s Saved Shows
   */
  async getUsersSavedShows(
    requestParameters: ShowsApiGetUsersSavedShowsRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PagingSavedShowObject> {
    const response = await this.getUsersSavedShowsRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
