name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - uses: pnpm/action-setup@v6.0.8
        with:
          cache: true
          run_install: |
            - args: ["--frozen-lockfile"]

      - uses: actions/setup-node@v6.4.0
        with:
          node-version: 24
          cache: pnpm

      - name: Lint
        run: pnpm lint && pnpm fmt --check

      - name: Install Playwright browsers
        run: pnpm --filter skeuomusic-react exec playwright install chromium --with-deps

      - name: Test
        run: pnpm --recursive test
