/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/solid-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RedirectSpotifyRouteImport } from './routes/redirect.spotify'
import { Route as PlayerSongsRouteImport } from './routes/player/songs'
import { Route as PlayerMoreRouteImport } from './routes/player/more'
import { Route as PlayerPlaylistsIndexRouteImport } from './routes/player/playlists/index'
import { Route as PlayerArtistsIndexRouteImport } from './routes/player/artists/index'
import { Route as PlayerAlbumsIndexRouteImport } from './routes/player/albums/index'
import { Route as PlayerArtistsArtistIdRouteImport } from './routes/player/artists/$artistId'
import { Route as PlayerAlbumsAlbumIdRouteImport } from './routes/player/albums/$albumId'
import { Route as PlayerArtistsArtistIdAlbumIdRouteImport } from './routes/player/artists/$artistId_.$albumId'
import { ServerRoute as ApiSpotifyAuthServerRouteImport } from './routes/api/spotify/auth'

const rootServerRouteImport = createServerRootRoute()

const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectSpotifyRoute = RedirectSpotifyRouteImport.update({
  id: '/redirect/spotify',
  path: '/redirect/spotify',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerSongsRoute = PlayerSongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerMoreRoute = PlayerMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerPlaylistsIndexRoute = PlayerPlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerArtistsIndexRoute = PlayerArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerAlbumsIndexRoute = PlayerAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerArtistsArtistIdRoute = PlayerArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerAlbumsAlbumIdRoute = PlayerAlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerArtistsArtistIdAlbumIdRoute =
  PlayerArtistsArtistIdAlbumIdRouteImport.update({
    id: '/artists/$artistId_/$albumId',
    path: '/artists/$artistId/$albumId',
    getParentRoute: () => PlayerRoute,
  } as any)
const ApiSpotifyAuthServerRoute = ApiSpotifyAuthServerRouteImport.update({
  id: '/api/spotify/auth',
  path: '/api/spotify/auth',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player': typeof PlayerRouteWithChildren
  '/player/more': typeof PlayerMoreRoute
  '/player/songs': typeof PlayerSongsRoute
  '/redirect/spotify': typeof RedirectSpotifyRoute
  '/player/albums/$albumId': typeof PlayerAlbumsAlbumIdRoute
  '/player/artists/$artistId': typeof PlayerArtistsArtistIdRoute
  '/player/albums': typeof PlayerAlbumsIndexRoute
  '/player/artists': typeof PlayerArtistsIndexRoute
  '/player/playlists': typeof PlayerPlaylistsIndexRoute
  '/player/artists/$artistId/$albumId': typeof PlayerArtistsArtistIdAlbumIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player': typeof PlayerRouteWithChildren
  '/player/more': typeof PlayerMoreRoute
  '/player/songs': typeof PlayerSongsRoute
  '/redirect/spotify': typeof RedirectSpotifyRoute
  '/player/albums/$albumId': typeof PlayerAlbumsAlbumIdRoute
  '/player/artists/$artistId': typeof PlayerArtistsArtistIdRoute
  '/player/albums': typeof PlayerAlbumsIndexRoute
  '/player/artists': typeof PlayerArtistsIndexRoute
  '/player/playlists': typeof PlayerPlaylistsIndexRoute
  '/player/artists/$artistId/$albumId': typeof PlayerArtistsArtistIdAlbumIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/player': typeof PlayerRouteWithChildren
  '/player/more': typeof PlayerMoreRoute
  '/player/songs': typeof PlayerSongsRoute
  '/redirect/spotify': typeof RedirectSpotifyRoute
  '/player/albums/$albumId': typeof PlayerAlbumsAlbumIdRoute
  '/player/artists/$artistId': typeof PlayerArtistsArtistIdRoute
  '/player/albums/': typeof PlayerAlbumsIndexRoute
  '/player/artists/': typeof PlayerArtistsIndexRoute
  '/player/playlists/': typeof PlayerPlaylistsIndexRoute
  '/player/artists/$artistId_/$albumId': typeof PlayerArtistsArtistIdAlbumIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/player'
    | '/player/more'
    | '/player/songs'
    | '/redirect/spotify'
    | '/player/albums/$albumId'
    | '/player/artists/$artistId'
    | '/player/albums'
    | '/player/artists'
    | '/player/playlists'
    | '/player/artists/$artistId/$albumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/player'
    | '/player/more'
    | '/player/songs'
    | '/redirect/spotify'
    | '/player/albums/$albumId'
    | '/player/artists/$artistId'
    | '/player/albums'
    | '/player/artists'
    | '/player/playlists'
    | '/player/artists/$artistId/$albumId'
  id:
    | '__root__'
    | '/'
    | '/player'
    | '/player/more'
    | '/player/songs'
    | '/redirect/spotify'
    | '/player/albums/$albumId'
    | '/player/artists/$artistId'
    | '/player/albums/'
    | '/player/artists/'
    | '/player/playlists/'
    | '/player/artists/$artistId_/$albumId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerRoute: typeof PlayerRouteWithChildren
  RedirectSpotifyRoute: typeof RedirectSpotifyRoute
}
export interface FileServerRoutesByFullPath {
  '/api/spotify/auth': typeof ApiSpotifyAuthServerRoute
}
export interface FileServerRoutesByTo {
  '/api/spotify/auth': typeof ApiSpotifyAuthServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/spotify/auth': typeof ApiSpotifyAuthServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/spotify/auth'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/spotify/auth'
  id: '__root__' | '/api/spotify/auth'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiSpotifyAuthServerRoute: typeof ApiSpotifyAuthServerRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect/spotify': {
      id: '/redirect/spotify'
      path: '/redirect/spotify'
      fullPath: '/redirect/spotify'
      preLoaderRoute: typeof RedirectSpotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/songs': {
      id: '/player/songs'
      path: '/songs'
      fullPath: '/player/songs'
      preLoaderRoute: typeof PlayerSongsRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/more': {
      id: '/player/more'
      path: '/more'
      fullPath: '/player/more'
      preLoaderRoute: typeof PlayerMoreRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/playlists/': {
      id: '/player/playlists/'
      path: '/playlists'
      fullPath: '/player/playlists'
      preLoaderRoute: typeof PlayerPlaylistsIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/artists/': {
      id: '/player/artists/'
      path: '/artists'
      fullPath: '/player/artists'
      preLoaderRoute: typeof PlayerArtistsIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/albums/': {
      id: '/player/albums/'
      path: '/albums'
      fullPath: '/player/albums'
      preLoaderRoute: typeof PlayerAlbumsIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/artists/$artistId': {
      id: '/player/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/player/artists/$artistId'
      preLoaderRoute: typeof PlayerArtistsArtistIdRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/albums/$albumId': {
      id: '/player/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/player/albums/$albumId'
      preLoaderRoute: typeof PlayerAlbumsAlbumIdRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/artists/$artistId_/$albumId': {
      id: '/player/artists/$artistId_/$albumId'
      path: '/artists/$artistId/$albumId'
      fullPath: '/player/artists/$artistId/$albumId'
      preLoaderRoute: typeof PlayerArtistsArtistIdAlbumIdRouteImport
      parentRoute: typeof PlayerRoute
    }
  }
}
declare module '@tanstack/solid-start/server' {
  interface ServerFileRoutesByPath {
    '/api/spotify/auth': {
      id: '/api/spotify/auth'
      path: '/api/spotify/auth'
      fullPath: '/api/spotify/auth'
      preLoaderRoute: typeof ApiSpotifyAuthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface PlayerRouteChildren {
  PlayerMoreRoute: typeof PlayerMoreRoute
  PlayerSongsRoute: typeof PlayerSongsRoute
  PlayerAlbumsAlbumIdRoute: typeof PlayerAlbumsAlbumIdRoute
  PlayerArtistsArtistIdRoute: typeof PlayerArtistsArtistIdRoute
  PlayerAlbumsIndexRoute: typeof PlayerAlbumsIndexRoute
  PlayerArtistsIndexRoute: typeof PlayerArtistsIndexRoute
  PlayerPlaylistsIndexRoute: typeof PlayerPlaylistsIndexRoute
  PlayerArtistsArtistIdAlbumIdRoute: typeof PlayerArtistsArtistIdAlbumIdRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerMoreRoute: PlayerMoreRoute,
  PlayerSongsRoute: PlayerSongsRoute,
  PlayerAlbumsAlbumIdRoute: PlayerAlbumsAlbumIdRoute,
  PlayerArtistsArtistIdRoute: PlayerArtistsArtistIdRoute,
  PlayerAlbumsIndexRoute: PlayerAlbumsIndexRoute,
  PlayerArtistsIndexRoute: PlayerArtistsIndexRoute,
  PlayerPlaylistsIndexRoute: PlayerPlaylistsIndexRoute,
  PlayerArtistsArtistIdAlbumIdRoute: PlayerArtistsArtistIdAlbumIdRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerRoute: PlayerRouteWithChildren,
  RedirectSpotifyRoute: RedirectSpotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSpotifyAuthServerRoute: ApiSpotifyAuthServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
